---
abstract: 'Modification of an identified PICA+ record'
author:
  - 'Jakob Voß <voss@gbv.de>'
build_requires:
  Test::Exception: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PICA-Modification
requires:
  Carp: 0
  Exporter: 0
  PICA::Record: 0
  Scalar::Util: 0
  Test::JSON::Entails: 0
  Test::More: 0.96
  Time::Stamp: 0
  parent: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/gbv/PICA-Modification/issues
  homepage: https://github.com/gbv/PICA-Modification
  repository: https://github.com/gbv/PICA-Modification.git
version: 0.134
